// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configGPB.proto

package org.sbe;

import java.io.ByteArrayOutputStream;
import java.io.ByteArrayOutputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.GeneratedMessageV3;
import java.io.IOException;

public final class ProtoClass {
  private ProtoClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Publication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 stationId = 1;</code>
     * @return The stationId.
     */
    int getStationId();

    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>int32 temp = 3;</code>
     * @return The temp.
     */
    int getTemp();

    /**
     * <code>float rain = 4;</code>
     * @return The rain.
     */
    float getRain();

    /**
     * <code>int32 wind = 5;</code>
     * @return The wind.
     */
    int getWind();

    /**
     * <code>string direction = 6;</code>
     * @return The direction.
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 6;</code>
     * @return The bytes for direction.
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>string date = 7;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 7;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code tutorial.Publication}
   */
  public static final class Publication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Publication)
      PublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Publication.newBuilder() to construct.
    private Publication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public Publication() {
      city_ = "";
      direction_ = "";
      date_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Publication();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_tutorial_Publication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_tutorial_Publication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sbe.ProtoClass.Publication.class, org.sbe.ProtoClass.Publication.Builder.class);
    }

    public static final int STATIONID_FIELD_NUMBER = 1;
    private int stationId_ = 0;
    /**
     * <code>int32 stationId = 1;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public int getStationId() {
      return stationId_;
    }

    public static final int CITY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMP_FIELD_NUMBER = 3;
    private int temp_ = 0;
    /**
     * <code>int32 temp = 3;</code>
     * @return The temp.
     */
    @java.lang.Override
    public int getTemp() {
      return temp_;
    }

    public static final int RAIN_FIELD_NUMBER = 4;
    private float rain_ = 0F;
    /**
     * <code>float rain = 4;</code>
     * @return The rain.
     */
    @java.lang.Override
    public float getRain() {
      return rain_;
    }

    public static final int WIND_FIELD_NUMBER = 5;
    private int wind_ = 0;
    /**
     * <code>int32 wind = 5;</code>
     * @return The wind.
     */
    @java.lang.Override
    public int getWind() {
      return wind_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object direction_ = "";
    /**
     * <code>string direction = 6;</code>
     * @return The direction.
     */
    @java.lang.Override
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 6;</code>
     * @return The bytes for direction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 7;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 7;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(ByteArrayOutputStream output)
                        throws java.io.IOException {

      CodedOutputStream codedOutput = CodedOutputStream.newInstance(output);

      if (stationId_ != 0) {
        codedOutput.writeInt32(1, stationId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(CodedOutputStream.newInstance(output), 2, city_);
      }
      if (temp_ != 0) {
        codedOutput.writeInt32(3, temp_);
      }
      if (java.lang.Float.floatToRawIntBits(rain_) != 0) {
        codedOutput.writeFloat(4, rain_);
      }
      if (wind_ != 0) {
        codedOutput.writeInt32(5, wind_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(CodedOutputStream.newInstance(output), 6, direction_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(CodedOutputStream.newInstance(output), 7, date_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stationId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (temp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, temp_);
      }
      if (java.lang.Float.floatToRawIntBits(rain_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, rain_);
      }
      if (wind_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, wind_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, direction_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, date_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sbe.ProtoClass.Publication)) {
        return super.equals(obj);
      }
      org.sbe.ProtoClass.Publication other = (org.sbe.ProtoClass.Publication) obj;

      if (getStationId()
          != other.getStationId()) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (getTemp()
          != other.getTemp()) return false;
      if (java.lang.Float.floatToIntBits(getRain())
          != java.lang.Float.floatToIntBits(
              other.getRain())) return false;
      if (getWind()
          != other.getWind()) return false;
      if (!getDirection()
          .equals(other.getDirection())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getStationId();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + TEMP_FIELD_NUMBER;
      hash = (53 * hash) + getTemp();
      hash = (37 * hash) + RAIN_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRain());
      hash = (37 * hash) + WIND_FIELD_NUMBER;
      hash = (53 * hash) + getWind();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sbe.ProtoClass.Publication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.sbe.ProtoClass.Publication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.sbe.ProtoClass.Publication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sbe.ProtoClass.Publication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sbe.ProtoClass.Publication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Publication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Publication)
        org.sbe.ProtoClass.PublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_tutorial_Publication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_tutorial_Publication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sbe.ProtoClass.Publication.class, org.sbe.ProtoClass.Publication.Builder.class);
      }

      // Construct using org.sbe.ProtoClass.Publication.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stationId_ = 0;
        city_ = "";
        temp_ = 0;
        rain_ = 0F;
        wind_ = 0;
        direction_ = "";
        date_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_tutorial_Publication_descriptor;
      }

      @java.lang.Override
      public org.sbe.ProtoClass.Publication getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.sbe.ProtoClass.Publication build() {
        org.sbe.ProtoClass.Publication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sbe.ProtoClass.Publication buildPartial() {
        org.sbe.ProtoClass.Publication result = new org.sbe.ProtoClass.Publication(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.sbe.ProtoClass.Publication result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stationId_ = stationId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.temp_ = temp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.rain_ = rain_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.wind_ = wind_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.direction_ = direction_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sbe.ProtoClass.Publication) {
          return mergeFrom((org.sbe.ProtoClass.Publication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sbe.ProtoClass.Publication other) {
        if (other == getDefaultInstance()) return this;
        if (other.getStationId() != 0) {
          setStationId(other.getStationId());
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getTemp() != 0) {
          setTemp(other.getTemp());
        }
        if (other.getRain() != 0F) {
          setRain(other.getRain());
        }
        if (other.getWind() != 0) {
          setWind(other.getWind());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                stationId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                temp_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 37: {
                rain_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 40: {
                wind_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                direction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int stationId_ ;
      /**
       * <code>int32 stationId = 1;</code>
       * @return The stationId.
       */
      @java.lang.Override
      public int getStationId() {
        return stationId_;
      }
      /**
       * <code>int32 stationId = 1;</code>
       * @param value The stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationId(int value) {

        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stationId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStationId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int temp_ ;
      /**
       * <code>int32 temp = 3;</code>
       * @return The temp.
       */
      @java.lang.Override
      public int getTemp() {
        return temp_;
      }
      /**
       * <code>int32 temp = 3;</code>
       * @param value The temp to set.
       * @return This builder for chaining.
       */
      public Builder setTemp(int value) {

        temp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 temp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        temp_ = 0;
        onChanged();
        return this;
      }

      private float rain_ ;
      /**
       * <code>float rain = 4;</code>
       * @return The rain.
       */
      @java.lang.Override
      public float getRain() {
        return rain_;
      }
      /**
       * <code>float rain = 4;</code>
       * @param value The rain to set.
       * @return This builder for chaining.
       */
      public Builder setRain(float value) {

        rain_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float rain = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRain() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rain_ = 0F;
        onChanged();
        return this;
      }

      private int wind_ ;
      /**
       * <code>int32 wind = 5;</code>
       * @return The wind.
       */
      @java.lang.Override
      public int getWind() {
        return wind_;
      }
      /**
       * <code>int32 wind = 5;</code>
       * @param value The wind to set.
       * @return This builder for chaining.
       */
      public Builder setWind(int value) {

        wind_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 wind = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWind() {
        bitField0_ = (bitField0_ & ~0x00000010);
        wind_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 6;</code>
       * @return The direction.
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 6;</code>
       * @return The bytes for direction.
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 6;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        direction_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        direction_ = getDefaultInstance().getDirection();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 6;</code>
       * @param value The bytes for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        direction_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 7;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 7;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 7;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 7;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Publication)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Publication)
    private static final org.sbe.ProtoClass.Publication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sbe.ProtoClass.Publication();
    }

    public static org.sbe.ProtoClass.Publication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Publication>
        PARSER = new com.google.protobuf.AbstractParser<Publication>() {
      @java.lang.Override
      public Publication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Publication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Publication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sbe.ProtoClass.Publication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Publication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Publication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017configGPB.proto\022\010tutorial\"y\n\013Publicati" +
      "on\022\021\n\tstationId\030\001 \001(\005\022\014\n\004city\030\002 \001(\t\022\014\n\004t" +
      "emp\030\003 \001(\005\022\014\n\004rain\030\004 \001(\002\022\014\n\004wind\030\005 \001(\005\022\021\n" +
      "\tdirection\030\006 \001(\t\022\014\n\004date\030\007 \001(\tBB\n\007org.sb" +
      "eB\nProtoClass\252\002*Google.Protobuf.Examples" +
      ".ProtoClassExampleb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Publication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Publication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Publication_descriptor,
        new java.lang.String[] { "StationId", "City", "Temp", "Rain", "Wind", "Direction", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
